### PR TITLE
178 display watering of plants on homepage

### PR DESCRIPTION
**Pull request by Ruhsi**

### CODE REVIEW

**Comment by ErhardSiegl** [comment]
The
```
@Entity("habarama")
public class WateringData {
```
is the same collection as 
```
@Entity("habarama")
public class SensorData {
```
Shouldn't we use a different collection? The name "habarama" is not good for either of them now that we have more than one collection.

**Comment by Ruhsi** [comment]
I know, but the `MongoDbProducer`-class let's you only work with one collection ('habarama'). And I didn't dare to  rewrite/change the Producer.
I described this issue (and others) in the comment below the task. https://github.com/Gepardec/Hogarama/issues/178

**Comment by ErhardSiegl** [comment]
Are you sure about this? In pull request #175 I used another Entity/Index/Collection (whatever they call this in Mongo) and it seemed to work.

**Comment by Ruhsi** [comment]
hmm I think so..
in MongoDbProducer-Class it says:

```
public class MongoDbProducer {
        private static final String COLLECTION = "habarama";

        @Produces
	public MongoCollection<Document> getCollection() {
		MongoDatabase dataBase = getClient().getDatabase(HOGAJAMA_DB);
		return dataBase.getCollection(COLLECTION);
	}
}
```
So it always returns 'habarama'-collection when injecting the collection, if I'm right.

**Comment by ErhardSiegl** [comment]
Thats not good, however I think you don't need getCollection(). See https://github.com/Gepardec/Hogarama/blob/da74efda984b328e67bb1b918c5052a8b7d7787a/Hogajama/hogajama-services/src/main/java/com/gepardec/hogarama/service/dao/MongoWateringConfigDAO.java

**Comment by Ruhsi** [comment]
Yeah, I've just seen it. It works, when using the `Datastore` and not the collection itself.

**Pull request merged**
